### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Aashiq2691** [sevensc/typescript-string-operations#11]
Currently there are no options to pass the string array as argument and get it formatted like below.

string[] args = ['Hello', 'World']
string sayHello = String.Format("{0}, {1}!", args)

Output : Hello, World!

Current output: Hello, World, undefined!

Is this feature will be availble any time soon.

**Comment by aequi42** [comment]
What happens if you invoke `String.Format("{0},{1}!", ...args)`?

**Comment by Aashiq2691** [comment]
Hi aequi42,

yes it works now by invoking the way you mentioned above.

Thanks a lot!
