### ISSUE TITLE
How import String module?

### ISSUE THREAD

**Issue by gabrielizalo** [sevensc/typescript-string-operations#4]
Hello,
How is the way I import String module into my TS file?

I have imported in this way into my /src/myLib/ts:
```
import { String } from "../node_modules/typescript-string-operations/source/source";
```
Is this correct or I theres a better way?

Thanks

**Comment by sevensc** [comment]
Hey, sorry for the delay. I just released a package where you can just write:

`import { String } from "typescript-string-operations";`

**Comment by StingyJack** [comment]
Adding this to the package.json and trying to use it in the latter example gives the error `TS2307	(TS) Cannot find module 'typescript-string-operations'.`

Is there some other specific configuration (module type/target/etc) required to use this?
