### ISSUE TITLE
node_modules\typescript-string-operations\index.ts is missing from the TypeScript compilation.

### ISSUE THREAD

**Issue by figueiredorj** [sevensc/typescript-string-operations#5]
Hi,

when trying to use this library in an angular 5 project has this message when compiling

'node_modules\typescript-string-operations\index.ts is missing from the TypeScript compilation.'

**Comment by sevensc** [comment]
How do you reference the Package?

**Comment by sevensc** [comment]
I could confirm that error and i will take care about it

**Comment by sevensc** [comment]
Should work fine now, thanks for your report!
