### ISSUE TITLE
formatNumber problem

### ISSUE THREAD

**Issue by martianma** [sevensc/typescript-string-operations#6]
`let url = /account/list?name={0}&group={1}&version={2}`
 `url = String.Format(url, “sss”, "", "");`

logout is
url = account/list?name=sss&group=000&version=000

I do not want 000, I want 0
what should I do？

private static formatNumber(input: number, formatTemplate: string): string {
        let count = formatTemplate.length;
        let stringValue = input.toString();
        if (count <= stringValue.length)
            return stringValue;
        let remainingCount = count - stringValue.length;
        remainingCount += 1; //Das Array muss einen Eintrag mehr als die benötigten Nullen besitzen
        return new Array(remainingCount).join('0') + stringValue;
    }

**Comment by sevensc** [comment]
This seems to be a bug. I let you know when this is fixed

**Comment by martianma** [comment]
ok,thank you

**Comment by martianma** [comment]
sorry,i want to the url like this
account/list?name=sss&group=&version=
empty string,not 0

**Comment by martianma** [comment]
It may be so

function parsePattern {
         .........

         if (typeof (arg) === 'number') {
            if (!isNaN(arg)) {
                return String.formatNumber(arg, match);
            }
        }
}

**Comment by sevensc** [comment]
If i would do that, i would loose the padding.

`let result = String.Format('{0:000}', 5); // would be just 5`

The problem was, that the method was using the braces for the length.

I fixed it, by checking if the pattern is a valid number.
There is a new test, and i deployed it to npm.

Your output should now look like that:
```
let url = /account/list?name={0}&group={1}&version={2}
"/account/list?name=sss&group=&version="
```

thank you for your report!
