### ISSUE TITLE
Importing the module creates TS2307 compile errors

### ISSUE THREAD

**Issue by StingyJack** [sevensc/typescript-string-operations#8]
I added this to the package.json and added an `import { String } from "typescript-string-operations";` to an existing ts file, and it gives the error TS2307 (TS) Cannot find module 'typescript-string-operations' in addition to breaking much of the rest of the module.

Is there some other specific configuration (module type/target/etc) required to use this?

Here is what I had
![image](https://user-images.githubusercontent.com/15381181/37566780-124696a4-2a94-11e8-85d9-f30fb91a40ae.png)

Then I added the import and tried to use the `String.Empty;`, but as soon as I build it, the rest of the classes in the module cannot be found.
![image](https://user-images.githubusercontent.com/15381181/37566820-7e94185e-2a94-11e8-9fc6-979173353518.png)

This could be something I am not understanding generally about typescript or module loading, but if you can point me in the right direction I would appreciate it.

**Comment by sevensc** [comment]
Did you install the last npm-package?

**Comment by sevensc** [comment]
And which module loader do you use?

**Comment by StingyJack** [comment]
I don't think I named a specific module loader. This is the tsconfig.json
```
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "alwaysStrict": true,
    "noImplicitReturns": true,
    "pretty": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "outDir": "dist",
    "moduleResolution": "classic"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ],
  "include": ["src/*.ts"]
  
}
```
And I installed it by adding the dependency to my package.json and waiting for the package to show up in my node_modules folder. 
```
 "dependencies": {
    "typescript": "2.7.2",
    "typescript-string-operations": "1.2.4" 
  }
```
The VS output window for NPM shows it getting the package and doesnt report any issues
```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\npm.CMD" install
my.ui@7.6.2 c:\tfs\mugglemagic\Trunk\Source\my.UI
└── typescript-string-operations@1.2.4 
npm WARN EPACKAGEJSON my.ui@7.6.2 No repository field.
```

**Comment by sevensc** [comment]
The reason is, thay you are using the "moduleResolution" flag, which is set to classic.
Try to remove the flag, or change to "node". What happens then?

**Comment by StingyJack** [comment]
If i remove that line from the tsconfig.json file, and place the import declaration outside the my namespace i get the TS2304 errors again, as well as "TS2307 cannot find module "typescript-string-operations".

Moving the import statement to inside the namespace does not cause the TS2304 errors, but does still have the TS2307, with the addition of a "TS1147 - import declarations in a namespace cannot reference a module". So I'm guessing that import is not the way to go, despite having other imports inside the namespace that are just fine for TS.
![image](https://user-images.githubusercontent.com/15381181/37596395-672f7f32-2b52-11e8-81fe-75624569017a.png)

Changing the module resolution to "node" results in the same behavior for both inside and outside the namespace.

I definitely have the module present. 
![image](https://user-images.githubusercontent.com/15381181/37596492-b761205a-2b52-11e8-80a8-05d0d30dc221.png)

**Comment by sevensc** [comment]
I´m not sure how to reproduce this, can you please provide some samples of your project?
Please try to import some other npm-packages if you get the same error.

**Comment by sevensc** [comment]
Any updates? @StingyJack

**Comment by StingyJack** [comment]
I use namespaces in my ts files, like `export namespace My.program.yadda`

Does that make a difference?

**Comment by sevensc** [comment]
Try a separate file without a namespace, import the package and see if it is still not working.

> Does that make a difference?

 You should not mix them, but see [this ](https://stackoverflow.com/a/38666021/5874913) answer for more informations about the difference. Or the [docs](https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html).
Did you try it already without VS 2017? I recommend using Visual Studio Code.

If you could provide a sample, i can check for myself what is wrong.

**Comment by StingyJack** [comment]
Thanks for that info, I'd been looking at it from a c style language perspective, where I can reference something externally but still organize my own code in a different way. I'll have to re-think my approach once my mind can better sort out how the one influences or dictates the other. 

I do use VSCode for markdown editing, but until it properly supports the msbuild project system (or at least doesnt have a crummy posh host process) its not really a viable option for me.

**Comment by sevensc** [comment]
You can reference any package you want, it shouldn’t affect your own structure at all. 
It is still possible, that there is a problem with the package.
if there is still anything else, feel free to contact me or reopen the issue.
